import { useState, useMemo } from 'react';
import { useParams } from 'react-router-dom';
import useSWR from 'swr';
import { fetchProfilesAPI, createProfileAPI, renameProfileAPI, deleteProfileAPI, syncAllProfilesAPI, revalidateRouterCache } from '../../api';
import { useLanguage } from '../../context/LanguageContext';
import { useModal } from '../../context/ModalContext';
import {
  Layers,
  Clock,
  HardDrive,
  Plus,
  Loader2,
  Tag,
  Shield,
  Trash2,
  Pencil,
  X,
  DollarSign,
  CheckCircle2,
  AlertCircle,
  Zap,
  RefreshCw,
} from 'lucide-react';

interface Profile {
  '.id': string;
  id?: string;
  name: string;
  validity?: string;
  limitMB?: number;
  isUnlimited?: boolean;
  printLabel?: string;
  revenue?: number | string;
  price?: number | string;
}

const parseValidity = (str?: string) => {
  if (!str) {
    return { num: 1, unit: 'd', isUnl: false };
  }
  const s = str.trim().toLowerCase();
  if (s === '0d' || s === '0h' || s === '0m' || s === '0' || s === 'unlimited' || s === 'none') {
    return { num: 0, unit: '', isUnl: true };
  }
  const match = s.match(/^(\d+)\s*([a-zA-Z]+)?$/);
  if (match) {
    const num = parseInt(match[1], 10) || 1;
    if (num === 0) {
      return { num: 0, unit: '', isUnl: true };
    }
    const u = (match[2] || 'd').toLowerCase();
    const unit = ['m', 'h', 'd', 'w'].includes(u) ? u : 'd';
    return { num, unit, isUnl: false };
  }
  return { num: 1, unit: 'd', isUnl: false };
};

const generateDefaultProfileName = (
  isUnlimitedTime: boolean,
  validityNum: number,
  validityUnit: string,
  isUnlimitedData: boolean,
  limitMB: number | undefined,
  isCustomLimit: boolean,
  customVal: number | string,
  customUnit: 'MB' | 'GB',
  isArabic: boolean
): string => {
  let timeStr = '';
  if (isUnlimitedTime) {
    timeStr = isArabic ? 'بدون حد' : 'Unlimited';
  } else {
    const num = validityNum || 1;
    const unit = (validityUnit || 'd').toLowerCase();
    if (isArabic) {
      let unitLabel = 'يوم';
      if (unit === 'm') unitLabel = num >= 3 && num <= 10 ? 'دقائق' : 'دقيقة';
      if (unit === 'h') unitLabel = num >= 3 && num <= 10 ? 'ساعات' : 'ساعة';
      if (unit === 'd') unitLabel = num >= 3 && num <= 10 ? 'أيام' : 'يوم';
      if (unit === 'w') unitLabel = num >= 3 && num <= 10 ? 'أسابيع' : 'أسبوع';
      timeStr = `${num} ${unitLabel}`;
    } else {
      let unitLabel = 'D';
      if (unit === 'm') unitLabel = 'M';
      if (unit === 'h') unitLabel = 'H';
      if (unit === 'd') unitLabel = 'D';
      if (unit === 'w') unitLabel = 'W';
      timeStr = `${num}${unitLabel}`;
    }
  }

  let dataStr = '';
  if (!isUnlimitedData) {
    let effectiveMB: number | undefined = undefined;
    if (isCustomLimit) {
      if (customVal !== '' && !isNaN(Number(customVal))) {
        effectiveMB = customUnit === 'GB' ? Number(customVal) * 1024 : Number(customVal);
      }
    } else if (limitMB) {
      effectiveMB = limitMB;
    }

    if (effectiveMB && effectiveMB > 0) {
      if (effectiveMB >= 1024 && effectiveMB % 1024 === 0) {
        const gb = effectiveMB / 1024;
        dataStr = isArabic ? `${gb} جيجا` : `${gb}GB`;
      } else {
        dataStr = isArabic ? `${effectiveMB} ميجا` : `${effectiveMB}MB`;
      }
    }
  }

  if (timeStr && dataStr) {
    if (isUnlimitedTime && dataStr) {
      return dataStr;
    }
    return `${timeStr} ${dataStr}`;
  }
  if (timeStr) {
    return timeStr;
  }
  if (dataStr) {
    return dataStr;
  }
  return isArabic ? 'بروفايل جديد' : 'New Profile';
};

export default function ProfilesPage() {
  const { routerId } = useParams<{ routerId: string }>();
  const { t, isRtl } = useLanguage();
  const { showConfirm, showAlert } = useModal();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingProfile, setEditingProfile] = useState<Profile | null>(null);

  // Form State
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);
  const [validityNum, setValidityNum] = useState<number>(1);
  const [validityUnit, setValidityUnit] = useState<string>('d');
  const [isUnlimitedTime, setIsUnlimitedTime] = useState(false);

  const [limitMB, setLimitMB] = useState<number | undefined>(undefined);
  const [isUnlimited, setIsUnlimited] = useState(true);
  const [isCustomLimit, setIsCustomLimit] = useState(false);
  const [customVal, setCustomVal] = useState<number | string>('');
  const [customUnit, setCustomUnit] = useState<'MB' | 'GB'>('GB');
  const [revenue, setRevenue] = useState<string | number>('');

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSyncingAll, setIsSyncingAll] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');
  const [warningModalData, setWarningModalData] = useState<{ profileName: string; userCount: number; message?: string } | null>(null);

  const handleSyncAllProfiles = async () => {
    if (!routerId || isSyncingAll) return;
    try {
      setIsSyncingAll(true);
      const res = await syncAllProfilesAPI(routerId);
      revalidateRouterCache(routerId);
      await mutate();
      setSuccessMsg(isRtl ? `تم تحديث وقفل الماك لجميع البروفايلات (${res.count}) بنجاح` : `Successfully updated & locked MAC on all ${res.count} profiles!`);
      setTimeout(() => setSuccessMsg(''), 4000);
    } catch (err: any) {
      setErrorMsg(err?.message || 'Failed to sync profiles');
      setTimeout(() => setErrorMsg(''), 4000);
    } finally {
      setIsSyncingAll(false);
    }
  };

  const { data: profiles, isLoading, mutate } = useSWR(
    routerId ? `router-profiles-${routerId}` : null,
    () => fetchProfilesAPI(routerId!),
    { revalidateOnFocus: true }
  );

  const profileList: Profile[] = useMemo(() => {
    if (!Array.isArray(profiles)) return [];
    return profiles.filter((p) => p.name && p.name.toLowerCase() !== 'default');
  }, [profiles]);

  // Data Limit Presets
  const dataPresets = [
    { label: '500 MB', mb: 500 },
    { label: '1 GB', mb: 1024 },
    { label: '2 GB', mb: 2048 },
    { label: '5 GB', mb: 5120 },
  ];

  // Telemetry counts
  const totalProfiles = profileList.length;
  const unlimitedCount = profileList.filter((p) => p.isUnlimited || !p.limitMB).length;
  const limitedCount = totalProfiles - unlimitedCount;

  // Helper to update auto-generated profile name if auto-generation is active
  const updateAutoNameIfNeeded = (
    unlTime = isUnlimitedTime,
    vNum = validityNum,
    vUnit = validityUnit,
    unlData = isUnlimited,
    lMB = limitMB,
    isCustom = isCustomLimit,
    cVal = customVal,
    cUnit = customUnit
  ) => {
    if (!editingProfile && isNameAutoGenerated) {
      const newAutoName = generateDefaultProfileName(
        unlTime,
        vNum,
        vUnit,
        unlData,
        lMB,
        isCustom,
        cVal,
        cUnit,
        isRtl
      );
      setName(newAutoName);
    }
  };

  // Open modal for Create
  const handleOpenCreateModal = () => {
    setEditingProfile(null);
    setIsNameAutoGenerated(true);
    const initialName = generateDefaultProfileName(false, 1, 'd', true, undefined, false, '', 'GB', isRtl);
    setName(initialName);
    setValidityNum(1);
    setValidityUnit('d');
    setIsUnlimitedTime(false);
    setLimitMB(undefined);
    setIsUnlimited(true);
    setIsCustomLimit(false);
    setCustomVal('');
    setCustomUnit('GB');
    setRevenue('');
    setErrorMsg('');
    setIsModalOpen(true);
  };

  // Open modal for Edit
  const handleOpenEditModal = (p: Profile) => {
    setEditingProfile(p);
    setIsNameAutoGenerated(false);
    setName(p.name || '');
    const { num, unit, isUnl } = parseValidity(p.validity);
    setIsUnlimitedTime(isUnl);
    setValidityNum(isUnl ? 1 : num);
    setValidityUnit(isUnl ? 'd' : unit);
    
    const profileIsUnl = p.isUnlimited ?? !p.limitMB;
    setIsUnlimited(profileIsUnl);
    setLimitMB(p.limitMB);

    if (!profileIsUnl && p.limitMB) {
      const isPreset = dataPresets.some((dp) => dp.mb === p.limitMB);
      setIsCustomLimit(!isPreset);
      if (p.limitMB % 1024 === 0) {
        setCustomUnit('GB');
        setCustomVal(p.limitMB / 1024);
      } else {
        setCustomUnit('MB');
        setCustomVal(p.limitMB);
      }
    } else {
      setIsCustomLimit(false);
      setCustomVal('');
      setCustomUnit('GB');
    }

    const initialRev = p.revenue != null ? p.revenue : p.price != null ? p.price : '';
    setRevenue(initialRev !== '' ? String(initialRev) : '');
    setErrorMsg('');
    setIsModalOpen(true);
  };

  // Handle Form Submit (Create or Edit)
  const handleSubmitForm = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;

    setIsSubmitting(true);
    setErrorMsg('');
    setSuccessMsg('');

    const formattedValidity = isUnlimitedTime ? '0d' : `${validityNum || 1}${validityUnit || 'd'}`;
    const apiIsUnlimited = isUnlimitedTime && isUnlimited;

    const effectiveLimitMB = isUnlimited
      ? undefined
      : isCustomLimit
      ? customVal !== '' && !isNaN(Number(customVal))
        ? customUnit === 'GB'
          ? Math.round(Number(customVal) * 1024)
          : Math.round(Number(customVal))
        : undefined
      : limitMB
      ? Number(limitMB)
      : undefined;

    try {
      if (editingProfile) {
        // Edit Mode
        await renameProfileAPI(
          routerId!,
          editingProfile['.id'],
          name.trim(),
          undefined,
          revenue ? Number(revenue) : undefined,
          formattedValidity,
          effectiveLimitMB,
          apiIsUnlimited
        );
        setSuccessMsg(t('profiles.profileUpdated'));
      } else {
        // Create Mode
        await createProfileAPI(
          routerId!,
          name.trim(),
          formattedValidity,
          effectiveLimitMB,
          apiIsUnlimited,
          undefined,
          revenue ? Number(revenue) : undefined
        );
        setSuccessMsg(t('profiles.profileCreated'));
      }

      setIsModalOpen(false);
      mutate();
      if (routerId) revalidateRouterCache(routerId);
    } catch (err: any) {
      setErrorMsg(err?.message || (editingProfile ? t('profiles.couldNotUpdate') : t('profiles.couldNotCreate')));
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle Delete Profile
  const handleDeleteProfile = (p: Profile) => {
    const title = t('profiles.deleteConfirmTitle') || t('common.delete') || 'Delete Profile?';
    const message = (t('profiles.deleteConfirm') || 'Are you sure you want to delete profile "{name}"?').replace('{name}', p.name);

    showConfirm(title, message, async () => {
      setDeletingId(p['.id']);
      try {
        await deleteProfileAPI(routerId!, p['.id']);
        showAlert(t('common.success'), t('profiles.profileDeleted') || 'Profile deleted successfully', 'success');
        mutate();
        if (routerId) revalidateRouterCache(routerId);
      } catch (err: any) {
        if (err?.code === 'PROFILE_IN_USE' || err?.userCount || err?.message?.includes('assigned to') || err?.message?.includes('PROFILE_IN_USE')) {
          setWarningModalData({
            profileName: err.profileName || p.name,
            userCount: err.userCount || 1,
            message: err.message
          });
        } else {
          showAlert(t('common.error'), err?.message || 'Error deleting profile', 'error');
        }
      } finally {
        setDeletingId(null);
      }
    });
  };

  // Theme compatible styles
  const cardGlassStyle: React.CSSProperties = {
    background: 'var(--card-bg, rgba(255, 255, 255, 0.05))',
    border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.1))',
    borderRadius: '10px',
    padding: '10px 12px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    backdropFilter: 'blur(10px)',
    WebkitBackdropFilter: 'blur(10px)',
    color: 'var(--foreground)',
  };

  const modalOverlayStyle: React.CSSProperties = {
    position: 'fixed',
    inset: 0,
    zIndex: 999,
    background: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '14px',
  };

  const modalContainerStyle: React.CSSProperties = {
    background: 'var(--card-bg, #1e293b)',
    color: 'var(--foreground)',
    border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.15))',
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
    maxWidth: '420px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '16px',
    boxSizing: 'border-box',
    direction: isRtl ? 'rtl' : 'ltr',
  };

  const inputContainerStyle: React.CSSProperties = {
    position: 'relative',
    width: '100%',
  };

  const inputStyle: React.CSSProperties = {
    background: 'var(--input-bg, rgba(0, 0, 0, 0.2))',
    border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.12))',
    borderRadius: '8px',
    height: '32px',
    padding: isRtl ? '0 32px 0 10px' : '0 10px 0 32px',
    color: 'var(--foreground)',
    fontSize: '12px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };

  const selectStyle: React.CSSProperties = {
    background: 'var(--input-bg, rgba(0, 0, 0, 0.2))',
    border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.12))',
    borderRadius: '8px',
    height: '32px',
    padding: '0 10px',
    color: 'var(--foreground)',
    fontSize: '12px',
    outline: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
  };

  const embeddedIconStyle: React.CSSProperties = {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    [isRtl ? 'right' : 'left']: '10px',
    color: 'var(--text-muted)',
    pointerEvents: 'none',
  };

  const validityPresets = [
    { label: t('profiles.unlimitedTime') || 'Unlimited Time', num: 0, unit: '', isUnl: true },
    { label: `1 ${t('profiles.unitHours') || 'Hour'}`, num: 1, unit: 'h', isUnl: false },
    { label: `12 ${t('profiles.unitHours') || 'Hours'}`, num: 12, unit: 'h', isUnl: false },
    { label: `1 ${t('profiles.unitDays') || 'Day'}`, num: 1, unit: 'd', isUnl: false },
    { label: `7 ${t('profiles.unitDays') || 'Days'}`, num: 7, unit: 'd', isUnl: false },
    { label: `30 ${t('profiles.unitDays') || 'Days'}`, num: 30, unit: 'd', isUnl: false },
  ];

  return (
    <div
      className="responsive-container"
      style={{
        direction: isRtl ? 'rtl' : 'ltr',
      }}
    >
      {/* ─── Page Header ─── */}
      <div className="responsive-card" style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'nowrap',
        gap: '8px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0 }}>
          <div style={{
            width: '32px',
            height: '32px',
            borderRadius: '9px',
            background: 'linear-gradient(135deg, rgba(59,130,246,0.2) 0%, rgba(37,99,235,0.4) 100%)',
            color: '#3b82f6',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            border: '1px solid rgba(59,130,246,0.3)',
            flexShrink: 0
          }}>
            <Layers size={16} />
          </div>
          <div style={{ minWidth: 0, flex: 1 }}>
            <h2 style={{ margin: 0, fontSize: '14px', fontWeight: 800, color: 'var(--foreground)', letterSpacing: '-0.2px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {t('profiles.title')}
            </h2>
          </div>
        </div>

        <button
          onClick={handleOpenCreateModal}
          style={{
            background: 'linear-gradient(135deg, var(--primary, #3b82f6) 0%, #2563eb 100%)',
            color: '#ffffff',
            border: 'none',
            borderRadius: '8px',
            padding: '6px 10px',
            fontSize: '11px',
            fontWeight: 700,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '4px',
            boxShadow: '0 2px 6px rgba(37, 99, 235, 0.3)',
            flexShrink: 0,
            whiteSpace: 'nowrap',
          }}
        >
          <Plus size={13} />
          <span>{t('profiles.addProfileBtn')}</span>
        </button>
      </div>

      {/* Success Notification */}
      {successMsg && (
        <div
          style={{
            background: 'rgba(34, 197, 94, 0.12)',
            border: '1px solid rgba(34, 197, 94, 0.3)',
            borderRadius: '8px',
            padding: '8px 12px',
            color: '#4ade80',
            fontSize: '12px',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
          }}
        >
          <CheckCircle2 size={14} style={{ flexShrink: 0 }} />
          <span>{successMsg}</span>
        </div>
      )}

      {/* Telemetry Strip */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: '8px',
          marginBottom: '6px',
        }}
      >
        <div style={{ ...cardGlassStyle, padding: '8px 12px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div
            style={{
              width: '28px',
              height: '28px',
              borderRadius: '7px',
              background: 'rgba(59, 130, 246, 0.15)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#3b82f6',
              flexShrink: 0,
            }}
          >
            <Layers size={14} />
          </div>
          <div>
            <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontWeight: 500, display: 'block', lineHeight: 1 }}>
              {t('profiles.totalProfiles')}
            </span>
            <strong className="stat-value" style={{ color: 'var(--foreground)' }}>
              {totalProfiles}
            </strong>
          </div>
        </div>

        <div style={{ ...cardGlassStyle, padding: '8px 12px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div
            style={{
              width: '28px',
              height: '28px',
              borderRadius: '7px',
              background: 'rgba(34, 197, 94, 0.15)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#22c55e',
              flexShrink: 0,
            }}
          >
            <Zap size={14} />
          </div>
          <div>
            <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontWeight: 500, display: 'block', lineHeight: 1 }}>
              {t('profiles.unlimited')}
            </span>
            <strong className="stat-value" style={{ color: '#22c55e' }}>
              {unlimitedCount}
            </strong>
          </div>
        </div>

        <div style={{ ...cardGlassStyle, padding: '8px 12px', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div
            style={{
              width: '28px',
              height: '28px',
              borderRadius: '7px',
              background: 'rgba(168, 85, 247, 0.15)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#a855f7',
              flexShrink: 0,
            }}
          >
            <HardDrive size={14} />
          </div>
          <div>
            <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontWeight: 500, display: 'block', lineHeight: 1 }}>
              {t('profiles.trafficLimit')}
            </span>
            <strong className="stat-value" style={{ color: '#a855f7' }}>
              {limitedCount}
            </strong>
          </div>
        </div>
      </div>

      {/* Profiles Cards Grid */}
      {isLoading ? (
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
            gap: '12px',
          }}
        >
          {Array.from({ length: 6 }).map((_, i) => (
            <div
              key={i}
              style={{
                ...cardGlassStyle,
                display: 'flex',
                flexDirection: 'column',
                padding: '14px 16px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flex: 1 }}>
                  <div className="skeleton" style={{ width: '34px', height: '34px', borderRadius: '8px', flexShrink: 0 }} />
                  <div className="skeleton" style={{ width: '50%', height: '14px' }} />
                </div>
                <div style={{ display: 'flex', gap: '6px' }}>
                  <div className="skeleton" style={{ width: '28px', height: '28px', borderRadius: '6px' }} />
                  <div className="skeleton" style={{ width: '28px', height: '28px', borderRadius: '6px' }} />
                </div>
              </div>
              <div style={{ height: '1px', background: 'var(--glass-border, rgba(255, 255, 255, 0.08))', margin: '12px 0' }} />
              <div style={{ display: 'flex', gap: '12px' }}>
                <div className="skeleton" style={{ width: '35%', height: '12px' }} />
                <div className="skeleton" style={{ width: '35%', height: '12px' }} />
              </div>
            </div>
          ))}
        </div>
      ) : profileList.length === 0 ? (
        <div style={{ ...cardGlassStyle, padding: '24px', textAlign: 'center' }}>
          <Shield size={24} style={{ color: 'var(--text-muted)', opacity: 0.5, marginBottom: '6px' }} />
          <h4 style={{ margin: '0 0 2px', color: 'var(--foreground)', fontSize: '14px' }}>{t('profiles.noProfilesFound')}</h4>
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '11px' }}>{t('profiles.noProfilesDesc')}</p>
        </div>
      ) : (
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
            gap: '12px',
          }}
        >
          {profileList.map((profile) => {
            const isUnlVal = profile.validity === '0d' || profile.validity === '0' || profile.validity === '0h' || profile.validity?.toLowerCase() === 'unlimited';
            const displayValidity = isUnlVal ? t('profiles.unlimitedTime') : (profile.validity || '1d');

            return (
              <div
                key={profile['.id'] || profile.name}
                style={{
                  ...cardGlassStyle,
                  display: 'flex',
                  flexDirection: 'column',
                  padding: '14px 16px',
                  transition: 'transform 0.15s ease, box-shadow 0.15s ease',
                }}
              >
                {/* Header Row: Icon, Title, Revenue Tag & Actions */}
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', minWidth: 0, flex: 1 }}>
                    <div
                      style={{
                        width: '34px',
                        height: '34px',
                        borderRadius: '9px',
                        background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.2) 0%, rgba(37, 99, 235, 0.1) 100%)',
                        border: '1px solid rgba(59, 130, 246, 0.25)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: '#3b82f6',
                        flexShrink: 0,
                      }}
                    >
                      <Layers size={17} />
                    </div>

                    <div style={{ minWidth: 0, flex: 1 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', overflow: 'hidden' }}>
                        <strong style={{ fontSize: '14px', fontWeight: 700, color: 'var(--foreground)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                          {profile.name}
                        </strong>
                        {(() => {
                          const revVal = profile.revenue ?? profile.price;
                          const numRev = revVal != null && revVal !== '' ? Number(revVal) : NaN;
                          if (!isNaN(numRev) && numRev > 0) {
                            return (
                              <span style={{ fontSize: '11px', fontWeight: 700, color: '#22c55e', background: 'rgba(34, 197, 94, 0.12)', border: '1px solid rgba(34, 197, 94, 0.25)', padding: '1.5px 6px', borderRadius: '5px', flexShrink: 0 }}>
                                ${numRev.toFixed(2)}
                              </span>
                            );
                          }
                          return null;
                        })()}
                      </div>
                    </div>
                  </div>

                  {/* Actions: Edit & Delete Buttons */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0 }}>
                    <button
                      onClick={() => handleOpenEditModal(profile)}
                      title="Edit Profile"
                      style={{
                        background: 'rgba(255, 255, 255, 0.07)',
                        border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.12))',
                        borderRadius: '7px',
                        width: '28px',
                        height: '28px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: 'var(--foreground)',
                        cursor: 'pointer',
                        transition: 'background 0.15s ease',
                      }}
                    >
                      <Pencil size={13} />
                    </button>

                    <button
                      onClick={() => handleDeleteProfile(profile)}
                      disabled={deletingId === profile['.id']}
                      title="Delete Profile"
                      style={{
                        background: 'rgba(239, 68, 68, 0.1)',
                        border: '1px solid rgba(239, 68, 68, 0.2)',
                        borderRadius: '7px',
                        width: '28px',
                        height: '28px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: '#ef4444',
                        cursor: 'pointer',
                        transition: 'background 0.15s ease',
                      }}
                    >
                      {deletingId === profile['.id'] ? (
                        <Loader2 size={12} className="animate-spin" />
                      ) : (
                        <Trash2 size={13} />
                      )}
                    </button>
                  </div>
                </div>

                {/* Divider between Card Header & Detail Items */}
                <div style={{ height: '1px', background: 'var(--glass-border, rgba(255, 255, 255, 0.08))', margin: '10px 0' }} />

                {/* Detail Items Row */}
                <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '12px', fontSize: '11px', color: 'var(--text-muted)' }}>
                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', background: 'rgba(56, 189, 248, 0.08)', padding: '3px 8px', borderRadius: '6px', border: '1px solid rgba(56, 189, 248, 0.15)' }}>
                    <Clock size={12} style={{ color: '#38bdf8' }} />
                    <span style={{ color: 'var(--foreground)', fontWeight: 500 }}>{displayValidity}</span>
                  </div>

                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: '5px', background: 'rgba(168, 85, 247, 0.08)', padding: '3px 8px', borderRadius: '6px', border: '1px solid rgba(168, 85, 247, 0.15)' }}>
                    <HardDrive size={12} style={{ color: '#a855f7' }} />
                    <span style={{ color: 'var(--foreground)', fontWeight: 500 }}>
                      {profile.isUnlimited || !profile.limitMB ? t('profiles.unlimited') : `${profile.limitMB} MB`}
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ─── Create / Edit Profile Modal ─── */}
      {isModalOpen && (
        <div style={modalOverlayStyle}>
          <div style={modalContainerStyle}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Layers size={16} style={{ color: 'var(--primary, #3b82f6)' }} />
                <h3 style={{ margin: 0, fontSize: '15px', fontWeight: 700, color: 'var(--foreground)' }}>
                  {editingProfile ? t('profiles.editProfileTitle') : t('profiles.createProfileTitle')}
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setIsModalOpen(false)}
                style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}
              >
                <X size={16} />
              </button>
            </div>

            <form onSubmit={handleSubmitForm} style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {/* Profile Name */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '3px' }}>
                <label style={{ fontSize: '11px', fontWeight: 600, color: 'var(--foreground)' }}>
                  {t('profiles.nameLabel')} *
                </label>
                <div style={inputContainerStyle}>
                  <Layers size={13} style={embeddedIconStyle} />
                  <input
                    type="text"
                    required
                    value={name}
                    onChange={(e) => {
                      setIsNameAutoGenerated(false);
                      setName(e.target.value);
                    }}
                    placeholder={t('profiles.namePlaceholder')}
                    style={inputStyle}
                  />
                </div>
              </div>

              {/* Simplified Validity Picker with Unlimited Option */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <label style={{ fontSize: '11px', fontWeight: 600, color: 'var(--foreground)' }}>
                  {t('profiles.validityLabel')} *
                </label>
                {/* Presets */}
                <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
                  {validityPresets.map((vp) => {
                    const isSelected = vp.isUnl ? isUnlimitedTime : !isUnlimitedTime && validityNum === vp.num && validityUnit === vp.unit;
                    return (
                      <button
                        key={vp.label}
                        type="button"
                        onClick={() => {
                          if (vp.isUnl) {
                            setIsUnlimitedTime(true);
                            updateAutoNameIfNeeded(true, validityNum, validityUnit, isUnlimited, limitMB, isCustomLimit, customVal, customUnit);
                          } else {
                            setIsUnlimitedTime(false);
                            setValidityNum(vp.num);
                            setValidityUnit(vp.unit);
                            updateAutoNameIfNeeded(false, vp.num, vp.unit, isUnlimited, limitMB, isCustomLimit, customVal, customUnit);
                          }
                        }}
                        style={{
                          padding: '3px 8px',
                          borderRadius: '5px',
                          fontSize: '10px',
                          fontWeight: 600,
                          cursor: 'pointer',
                          background: isSelected ? 'var(--primary, #3b82f6)' : 'var(--input-bg, rgba(0, 0, 0, 0.15))',
                          color: isSelected ? '#ffffff' : 'var(--foreground)',
                          border: '1px solid ' + (isSelected ? 'var(--primary, #3b82f6)' : 'var(--glass-border, rgba(255, 255, 255, 0.1))'),
                        }}
                      >
                        {vp.label}
                      </button>
                    );
                  })}
                </div>

                {/* Direct Numeric Input + Unit Select Dropdown (disabled if unlimited) */}
                {!isUnlimitedTime && (
                  <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                    <div style={{ ...inputContainerStyle, flex: 1 }}>
                      <Clock size={13} style={embeddedIconStyle} />
                      <input
                        type="number"
                        min="1"
                        required={!isUnlimitedTime}
                        value={validityNum || ''}
                        onChange={(e) => {
                          const num = e.target.value ? Number(e.target.value) : 1;
                          setValidityNum(num);
                          updateAutoNameIfNeeded(isUnlimitedTime, num, validityUnit, isUnlimited, limitMB, isCustomLimit, customVal, customUnit);
                        }}
                        style={inputStyle}
                      />
                    </div>
                    <select
                      value={validityUnit}
                      onChange={(e) => {
                        const u = e.target.value;
                        setValidityUnit(u);
                        updateAutoNameIfNeeded(isUnlimitedTime, validityNum, u, isUnlimited, limitMB, isCustomLimit, customVal, customUnit);
                      }}
                      style={{ ...selectStyle, minWidth: '90px' }}
                    >
                      <option value="m">{t('profiles.unitMinutes') || 'Minutes'}</option>
                      <option value="h">{t('profiles.unitHours') || 'Hours'}</option>
                      <option value="d">{t('profiles.unitDays') || 'Days'}</option>
                      <option value="w">{t('profiles.unitWeeks') || 'Weeks'}</option>
                    </select>
                  </div>
                )}
              </div>

              {/* Data Limit Control */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', background: 'rgba(0, 0, 0, 0.12)', padding: '10px', borderRadius: '10px', border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.08))' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <HardDrive size={14} style={{ color: !isUnlimited ? '#a855f7' : 'var(--text-muted)' }} />
                    <div>
                      <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--foreground)', display: 'block' }}>
                        {t('profiles.limitDataTraffic')}
                      </span>
                      <span style={{ fontSize: '9px', color: 'var(--text-muted)', display: 'block' }}>
                        {isUnlimited
                          ? t('profiles.unlimitedDataDesc')
                          : t('profiles.limitedDataDesc')}
                      </span>
                    </div>
                  </div>

                  {/* Switch Toggle */}
                  <button
                    type="button"
                    role="switch"
                    aria-checked={!isUnlimited}
                    onClick={() => {
                      if (isUnlimited) {
                        setIsUnlimited(false);
                        const defaultMB = limitMB || 1024;
                        if (!limitMB) {
                          setLimitMB(1024);
                          setIsCustomLimit(false);
                        }
                        updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, false, defaultMB, false, customVal, customUnit);
                      } else {
                        setIsUnlimited(true);
                        updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, true, limitMB, isCustomLimit, customVal, customUnit);
                      }
                    }}
                    style={{
                      width: '38px',
                      height: '20px',
                      borderRadius: '10px',
                      background: !isUnlimited ? 'var(--primary, #3b82f6)' : 'rgba(255, 255, 255, 0.15)',
                      border: 'none',
                      cursor: 'pointer',
                      position: 'relative',
                      transition: 'background 0.2s ease',
                      padding: '2px',
                      flexShrink: 0,
                    }}
                  >
                    <div
                      style={{
                        width: '16px',
                        height: '16px',
                        borderRadius: '50%',
                        background: '#ffffff',
                        boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
                        transform: !isUnlimited ? (isRtl ? 'translateX(-18px)' : 'translateX(18px)') : 'translateX(0)',
                        transition: 'transform 0.2s ease',
                      }}
                    />
                  </button>
                </div>

                {/* If Limited Data Traffic is active (!isUnlimited) */}
                {!isUnlimited && (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', paddingTop: '4px', borderTop: '1px dashed var(--glass-border, rgba(255, 255, 255, 0.08))' }}>
                    <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
                      {dataPresets.map((dp) => {
                        const isSelected = !isCustomLimit && limitMB === dp.mb;
                        return (
                          <button
                            key={dp.label}
                            type="button"
                            onClick={() => {
                              setIsCustomLimit(false);
                              setLimitMB(dp.mb);
                              updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, false, dp.mb, false, customVal, customUnit);
                            }}
                            style={{
                              padding: '3px 8px',
                              borderRadius: '5px',
                              fontSize: '10px',
                              fontWeight: 600,
                              cursor: 'pointer',
                              background: isSelected ? 'var(--primary, #3b82f6)' : 'var(--input-bg, rgba(0, 0, 0, 0.15))',
                              color: isSelected ? '#ffffff' : 'var(--foreground)',
                              border: '1px solid ' + (isSelected ? 'var(--primary, #3b82f6)' : 'var(--glass-border, rgba(255, 255, 255, 0.1))'),
                              transition: 'all 0.15s ease',
                            }}
                          >
                            {dp.label}
                          </button>
                        );
                      })}

                      {/* Custom / Specific Limit Option Button */}
                      <button
                        type="button"
                        onClick={() => {
                          setIsCustomLimit(true);
                          let newMb = limitMB;
                          let newVal = customVal;
                          let newUnit = customUnit;
                          if (!customVal && limitMB) {
                            if (limitMB % 1024 === 0) {
                              newUnit = 'GB';
                              newVal = limitMB / 1024;
                            } else {
                              newUnit = 'MB';
                              newVal = limitMB;
                            }
                            setCustomUnit(newUnit);
                            setCustomVal(newVal);
                          } else if (!customVal && !limitMB) {
                            newUnit = 'GB';
                            newVal = 1;
                            newMb = 1024;
                            setCustomUnit(newUnit);
                            setCustomVal(newVal);
                            setLimitMB(newMb);
                          }
                          updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, false, newMb, true, newVal, newUnit);
                        }}
                        style={{
                          padding: '3px 8px',
                          borderRadius: '5px',
                          fontSize: '10px',
                          fontWeight: 600,
                          cursor: 'pointer',
                          background: isCustomLimit ? 'var(--primary, #3b82f6)' : 'var(--input-bg, rgba(0, 0, 0, 0.15))',
                          color: isCustomLimit ? '#ffffff' : 'var(--foreground)',
                          border: '1px solid ' + (isCustomLimit ? 'var(--primary, #3b82f6)' : 'var(--glass-border, rgba(255, 255, 255, 0.1))'),
                          transition: 'all 0.15s ease',
                        }}
                      >
                        {t('profiles.specificLimit')}
                      </button>
                    </div>

                    {/* Specific Data Limit input field */}
                    {isCustomLimit && (
                      <div style={{ display: 'flex', gap: '6px', alignItems: 'center', marginTop: '2px' }}>
                        <div style={{ ...inputContainerStyle, flex: 1 }}>
                          <HardDrive size={13} style={embeddedIconStyle} />
                          <input
                            type="number"
                            step="any"
                            min="0.1"
                            required={!isUnlimited && isCustomLimit}
                            value={customVal || ''}
                            onChange={(e) => {
                              const val = e.target.value ? parseFloat(e.target.value) : '';
                              setCustomVal(val);
                              let mbValue: number | undefined = undefined;
                              if (val !== '' && !isNaN(Number(val))) {
                                mbValue = customUnit === 'GB' ? Math.round(Number(val) * 1024) : Math.round(Number(val));
                                setLimitMB(mbValue);
                              } else {
                                setLimitMB(undefined);
                              }
                              updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, false, mbValue, true, val, customUnit);
                            }}
                            placeholder={customUnit === 'GB' ? 'e.g. 1.5' : 'e.g. 750'}
                            style={inputStyle}
                          />
                        </div>
                        <select
                          value={customUnit}
                          onChange={(e) => {
                            const newUnit = e.target.value as 'MB' | 'GB';
                            setCustomUnit(newUnit);
                            let mbValue: number | undefined = undefined;
                            if (customVal !== '' && !isNaN(Number(customVal))) {
                              mbValue = newUnit === 'GB' ? Math.round(Number(customVal) * 1024) : Math.round(Number(customVal));
                              setLimitMB(mbValue);
                            }
                            updateAutoNameIfNeeded(isUnlimitedTime, validityNum, validityUnit, false, mbValue, true, customVal, newUnit);
                          }}
                          style={{ ...selectStyle, minWidth: '75px' }}
                        >
                          <option value="MB">MB</option>
                          <option value="GB">GB</option>
                        </select>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Price Field */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '3px' }}>
                <label style={{ fontSize: '10px', fontWeight: 600, color: 'var(--foreground)' }}>
                  {t('profiles.priceLabel')}
                </label>
                <div style={inputContainerStyle}>
                  <DollarSign size={12} style={embeddedIconStyle} />
                  <input
                    type="number"
                    step="0.01"
                    min="0"
                    value={revenue}
                    onChange={(e) => setRevenue(e.target.value)}
                    placeholder="e.g. 5.00"
                    style={inputStyle}
                  />
                </div>
              </div>

              {/* Modal Actions */}
              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '6px', marginTop: '4px' }}>
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  style={{
                    background: 'var(--input-bg, rgba(0, 0, 0, 0.15))',
                    border: '1px solid var(--glass-border, rgba(255, 255, 255, 0.1))',
                    borderRadius: '6px',
                    padding: '6px 12px',
                    color: 'var(--foreground)',
                    fontSize: '11px',
                    cursor: 'pointer',
                  }}
                >
                  {t('profiles.cancelBtn')}
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  style={{
                    background: 'linear-gradient(135deg, var(--primary, #3b82f6) 0%, #2563eb 100%)',
                    color: '#ffffff',
                    border: 'none',
                    borderRadius: '6px',
                    padding: '6px 14px',
                    fontSize: '11px',
                    fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '4px',
                  }}
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 size={12} className="animate-spin" />
                      <span>{t('profiles.saving')}</span>
                    </>
                  ) : (
                    <span>{editingProfile ? t('profiles.updateBtn') : t('profiles.saveBtn')}</span>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Profile In Use Warning Modal */}
      {warningModalData && (
        <div style={modalOverlayStyle}>
          <div style={{ ...modalContainerStyle, maxWidth: '420px', border: '1px solid rgba(239, 68, 68, 0.4)' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#ef4444' }}>
                <AlertCircle size={20} />
                <h3 style={{ margin: 0, fontSize: '15px', fontWeight: 700, color: '#ef4444' }}>
                  {t('profiles.profileInUseTitle')}
                </h3>
              </div>
              <button
                onClick={() => setWarningModalData(null)}
                style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px' }}
              >
                <X size={16} />
              </button>
            </div>

            <div style={{ background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.2)', borderRadius: '8px', padding: '12px 14px', color: 'var(--foreground)', fontSize: '13px', lineHeight: 1.5, marginBottom: '16px' }}>
              {t('profiles.profileInUseDesc')
                .replace('{name}', warningModalData.profileName)
                .replace('{count}', String(warningModalData.userCount))}
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
              <button
                onClick={() => setWarningModalData(null)}
                style={{
                  background: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
                  color: '#ffffff',
                  border: 'none',
                  borderRadius: '6px',
                  padding: '7px 18px',
                  fontSize: '12px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  boxShadow: '0 2px 8px rgba(239, 68, 68, 0.3)'
                }}
              >
                {t('common.ok')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}